name: 'plugin-check'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-dev --prefer-dist --no-progress --no-interaction

    - name: Create distribution build
      run: |
        mkdir -p jwt-auth-pro-wp-rest-api
        rsync -a --exclude-from=.distignore ./ jwt-auth-pro-wp-rest-api/

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        repo-token: ''
        build-dir: './jwt-auth-pro-wp-rest-api'
        checks: ''
        exclude-checks: ''
        categories: 'plugin_repo'
        exclude-directories: 'tests/*'
        ignore-warnings: ''
        ignore-errors: ''
        include-experimental: ''
        wp-version: 'latest'
